/*
 * Catalog loader — loads and caches the pre-built anime-catalog.json.
 *
 * The JSON is generated by scripts/build-catalog.mjs and shipped as a static
 * asset. On first request we fetch it once, store the result in memory, and
 * reuse for every subsequent call. The browser cache handles cold reloads.
 *
 * We expose a promise-returning loader rather than a sync getter so the
 * caller controls its own suspense/loading state.
 */

/** @type {Promise<Catalog> | null} */
let cachedPromise = null;

/**
 * @typedef {object} CatalogEntry
 * @property {number} mal_id
 * @property {string} title
 * @property {string[]} synonyms
 * @property {string} type
 * @property {number | null} episodes
 * @property {string} status
 * @property {number | null} year
 * @property {string | null} season
 * @property {string | null} picture
 * @property {string | null} thumbnail
 * @property {string[]} tags
 */

/**
 * @typedef {object} Catalog
 * @property {string} generated_at
 * @property {string} release
 * @property {number} total
 * @property {CatalogEntry[]} data
 */

const catalogUrl = () => `${import.meta.env.BASE_URL}anime-catalog.json`;

/**
 * Load the bundled catalog. Cached after the first successful call so any
 * subsequent randomizer / detail lookup is synchronous against in-memory data.
 */
export const loadCatalog = () => {
    if (cachedPromise) return cachedPromise;

    cachedPromise = fetch(catalogUrl())
        .then((res) => {
            if (!res.ok) throw new Error(`Catalog HTTP ${res.status}`);
            return res.json();
        })
        .catch((err) => {
            // Reset the cache on failure so a subsequent retry can actually
            // try again — otherwise the rejection sticks forever.
            cachedPromise = null;
            throw err;
        });

    return cachedPromise;
};

/** Pick a uniformly random entry from the whole catalog. */
export const pickRandomFromCatalog = (catalog) => {
    const { data } = catalog;
    if (data.length === 0) return null;
    return data[Math.floor(Math.random() * data.length)];
};

/** Find a single entry by its MAL id. O(n) but the catalog is small enough. */
export const findInCatalog = (catalog, malId) =>
    catalog.data.find((entry) => entry.mal_id === malId) ?? null;
